// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: proto/seckillManager/seckillManager.proto

package seckillManager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeckillProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price     float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Num       int32   `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	StartTime string  `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string  `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Pic       string  `protobuf:"bytes,7,opt,name=pic,proto3" json:"pic,omitempty"`
	SecPrice  float32 `protobuf:"fixed32,8,opt,name=secPrice,proto3" json:"secPrice,omitempty"`
	SecDesc   string  `protobuf:"bytes,9,opt,name=secDesc,proto3" json:"secDesc,omitempty"`
	Pid       int32   `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *SeckillProduct) Reset() {
	*x = SeckillProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeckillProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillProduct) ProtoMessage() {}

func (x *SeckillProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillProduct.ProtoReflect.Descriptor instead.
func (*SeckillProduct) Descriptor() ([]byte, []int) {
	return file_proto_seckillManager_seckillManager_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillProduct) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SeckillProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeckillProduct) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeckillProduct) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SeckillProduct) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SeckillProduct) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *SeckillProduct) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SeckillProduct) GetSecPrice() float32 {
	if x != nil {
		return x.SecPrice
	}
	return 0
}

func (x *SeckillProduct) GetSecDesc() string {
	if x != nil {
		return x.SecDesc
	}
	return ""
}

func (x *SeckillProduct) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type SeckillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *SeckillProduct `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Code int32           `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string          `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SeckillResponse) Reset() {
	*x = SeckillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeckillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResponse) ProtoMessage() {}

func (x *SeckillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResponse.ProtoReflect.Descriptor instead.
func (*SeckillResponse) Descriptor() ([]byte, []int) {
	return file_proto_seckillManager_seckillManager_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillResponse) GetInfo() *SeckillProduct {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SeckillResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SeckillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_proto_seckillManager_seckillManager_proto_rawDescGZIP(), []int{2}
}

func (x *IdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgResponse) Reset() {
	*x = MsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResponse) ProtoMessage() {}

func (x *MsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResponse.ProtoReflect.Descriptor instead.
func (*MsgResponse) Descriptor() ([]byte, []int) {
	return file_proto_seckillManager_seckillManager_proto_rawDescGZIP(), []int{3}
}

func (x *MsgResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MsgResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Seckill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid       int32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Num       int32   `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	StartTime string  `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string  `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Pic       string  `protobuf:"bytes,6,opt,name=pic,proto3" json:"pic,omitempty"`
	SecPrice  float32 `protobuf:"fixed32,7,opt,name=secPrice,proto3" json:"secPrice,omitempty"`
	SecDesc   string  `protobuf:"bytes,8,opt,name=secDesc,proto3" json:"secDesc,omitempty"`
}

func (x *Seckill) Reset() {
	*x = Seckill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seckill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seckill) ProtoMessage() {}

func (x *Seckill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seckill.ProtoReflect.Descriptor instead.
func (*Seckill) Descriptor() ([]byte, []int) {
	return file_proto_seckillManager_seckillManager_proto_rawDescGZIP(), []int{4}
}

func (x *Seckill) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Seckill) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Seckill) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Seckill) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Seckill) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *Seckill) GetSecPrice() float32 {
	if x != nil {
		return x.SecPrice
	}
	return 0
}

func (x *Seckill) GetSecDesc() string {
	if x != nil {
		return x.SecDesc
	}
	return ""
}

type SeckillEdit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid       int32   `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Num       int32   `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	StartTime string  `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string  `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Pic       string  `protobuf:"bytes,6,opt,name=pic,proto3" json:"pic,omitempty"`
	SecPrice  float32 `protobuf:"fixed32,7,opt,name=secPrice,proto3" json:"secPrice,omitempty"`
	SecDesc   string  `protobuf:"bytes,8,opt,name=secDesc,proto3" json:"secDesc,omitempty"`
}

func (x *SeckillEdit) Reset() {
	*x = SeckillEdit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeckillEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillEdit) ProtoMessage() {}

func (x *SeckillEdit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillEdit.ProtoReflect.Descriptor instead.
func (*SeckillEdit) Descriptor() ([]byte, []int) {
	return file_proto_seckillManager_seckillManager_proto_rawDescGZIP(), []int{5}
}

func (x *SeckillEdit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SeckillEdit) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SeckillEdit) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SeckillEdit) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SeckillEdit) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *SeckillEdit) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SeckillEdit) GetSecPrice() float32 {
	if x != nil {
		return x.SecPrice
	}
	return 0
}

func (x *SeckillEdit) GetSecDesc() string {
	if x != nil {
		return x.SecDesc
	}
	return ""
}

type SeckillsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Count int32             `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	List  []*SeckillProduct `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SeckillsResponse) Reset() {
	*x = SeckillsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeckillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillsResponse) ProtoMessage() {}

func (x *SeckillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillsResponse.ProtoReflect.Descriptor instead.
func (*SeckillsResponse) Descriptor() ([]byte, []int) {
	return file_proto_seckillManager_seckillManager_proto_rawDescGZIP(), []int{6}
}

func (x *SeckillsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SeckillsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SeckillsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SeckillsResponse) GetList() []*SeckillProduct {
	if x != nil {
		return x.List
	}
	return nil
}

type SeckillsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentPage int32 `protobuf:"varint,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize    int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *SeckillsRequest) Reset() {
	*x = SeckillsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeckillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillsRequest) ProtoMessage() {}

func (x *SeckillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seckillManager_seckillManager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillsRequest.ProtoReflect.Descriptor instead.
func (*SeckillsRequest) Descriptor() ([]byte, []int) {
	return file_proto_seckillManager_seckillManager_proto_rawDescGZIP(), []int{7}
}

func (x *SeckillsRequest) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *SeckillsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_proto_seckillManager_seckillManager_proto protoreflect.FileDescriptor

var file_proto_seckillManager_seckillManager_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x63,
	0x6b, 0x69, 0x6c, 0x6c, 0x22, 0xee, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x63, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x73, 0x65, 0x63, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63,
	0x44, 0x65, 0x73, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x44,
	0x65, 0x73, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x0f, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c,
	0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1b, 0x0a, 0x09, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xad, 0x01,
	0x0a, 0x07, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73, 0x65, 0x63, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x44, 0x65, 0x73, 0x63, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x44, 0x65, 0x73, 0x63, 0x22, 0xc1, 0x01,
	0x0a, 0x0b, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x64, 0x69, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x63, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73,
	0x65, 0x63, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x44, 0x65,
	0x73, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x44, 0x65, 0x73,
	0x63, 0x22, 0x7b, 0x0a, 0x10, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c,
	0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4f,
	0x0a, 0x0f, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x32,
	0xc0, 0x02, 0x0a, 0x08, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x44, 0x0a, 0x0b,
	0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x73, 0x65,
	0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e,
	0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x36, 0x0a, 0x0a, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x41, 0x64, 0x64,
	0x12, 0x10, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69,
	0x6c, 0x6c, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0a, 0x53, 0x65,
	0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x6c, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69,
	0x6c, 0x6c, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73,
	0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x44,
	0x6f, 0x45, 0x64, 0x69, 0x74, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e,
	0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x64, 0x69, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x65,
	0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0b, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c,
	0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65,
	0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_seckillManager_seckillManager_proto_rawDescOnce sync.Once
	file_proto_seckillManager_seckillManager_proto_rawDescData = file_proto_seckillManager_seckillManager_proto_rawDesc
)

func file_proto_seckillManager_seckillManager_proto_rawDescGZIP() []byte {
	file_proto_seckillManager_seckillManager_proto_rawDescOnce.Do(func() {
		file_proto_seckillManager_seckillManager_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_seckillManager_seckillManager_proto_rawDescData)
	})
	return file_proto_seckillManager_seckillManager_proto_rawDescData
}

var file_proto_seckillManager_seckillManager_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_seckillManager_seckillManager_proto_goTypes = []interface{}{
	(*SeckillProduct)(nil),   // 0: seckill.SeckillProduct
	(*SeckillResponse)(nil),  // 1: seckill.SeckillResponse
	(*IdRequest)(nil),        // 2: seckill.IdRequest
	(*MsgResponse)(nil),      // 3: seckill.MsgResponse
	(*Seckill)(nil),          // 4: seckill.Seckill
	(*SeckillEdit)(nil),      // 5: seckill.SeckillEdit
	(*SeckillsResponse)(nil), // 6: seckill.SeckillsResponse
	(*SeckillsRequest)(nil),  // 7: seckill.SeckillsRequest
}
var file_proto_seckillManager_seckillManager_proto_depIdxs = []int32{
	0, // 0: seckill.SeckillResponse.info:type_name -> seckill.SeckillProduct
	0, // 1: seckill.SeckillsResponse.list:type_name -> seckill.SeckillProduct
	7, // 2: seckill.Seckills.SeckillList:input_type -> seckill.SeckillsRequest
	4, // 3: seckill.Seckills.SecKillAdd:input_type -> seckill.Seckill
	2, // 4: seckill.Seckills.SeckillDel:input_type -> seckill.IdRequest
	5, // 5: seckill.Seckills.SeckillDoEdit:input_type -> seckill.SeckillEdit
	2, // 6: seckill.Seckills.SeckillInfo:input_type -> seckill.IdRequest
	6, // 7: seckill.Seckills.SeckillList:output_type -> seckill.SeckillsResponse
	3, // 8: seckill.Seckills.SecKillAdd:output_type -> seckill.MsgResponse
	3, // 9: seckill.Seckills.SeckillDel:output_type -> seckill.MsgResponse
	3, // 10: seckill.Seckills.SeckillDoEdit:output_type -> seckill.MsgResponse
	1, // 11: seckill.Seckills.SeckillInfo:output_type -> seckill.SeckillResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_seckillManager_seckillManager_proto_init() }
func file_proto_seckillManager_seckillManager_proto_init() {
	if File_proto_seckillManager_seckillManager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_seckillManager_seckillManager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeckillProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seckillManager_seckillManager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeckillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seckillManager_seckillManager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seckillManager_seckillManager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seckillManager_seckillManager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seckill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seckillManager_seckillManager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeckillEdit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seckillManager_seckillManager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeckillsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seckillManager_seckillManager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeckillsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_seckillManager_seckillManager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_seckillManager_seckillManager_proto_goTypes,
		DependencyIndexes: file_proto_seckillManager_seckillManager_proto_depIdxs,
		MessageInfos:      file_proto_seckillManager_seckillManager_proto_msgTypes,
	}.Build()
	File_proto_seckillManager_seckillManager_proto = out.File
	file_proto_seckillManager_seckillManager_proto_rawDesc = nil
	file_proto_seckillManager_seckillManager_proto_goTypes = nil
	file_proto_seckillManager_seckillManager_proto_depIdxs = nil
}
