// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	Registry(ctx context.Context, in *RegistryRequest, opts ...client.CallOption) (*Response, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*Response, error)
	SendEmail(ctx context.Context, in *EmailRequest, opts ...client.CallOption) (*Response, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Registry(ctx context.Context, in *RegistryRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.Registry", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.Login", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SendEmail(ctx context.Context, in *EmailRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.SendEmail", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Registry(context.Context, *RegistryRequest, *Response) error
	Login(context.Context, *LoginRequest, *Response) error
	SendEmail(context.Context, *EmailRequest, *Response) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Registry(ctx context.Context, in *RegistryRequest, out *Response) error
		Login(ctx context.Context, in *LoginRequest, out *Response) error
		SendEmail(ctx context.Context, in *EmailRequest, out *Response) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Registry(ctx context.Context, in *RegistryRequest, out *Response) error {
	return h.UserHandler.Registry(ctx, in, out)
}

func (h *userHandler) Login(ctx context.Context, in *LoginRequest, out *Response) error {
	return h.UserHandler.Login(ctx, in, out)
}

func (h *userHandler) SendEmail(ctx context.Context, in *EmailRequest, out *Response) error {
	return h.UserHandler.SendEmail(ctx, in, out)
}
